trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'Get configuration'

- bash: |
    mkdir code
    git clone https://github.com/carrier-io/dusty.git code/dusty
    git clone https://github.com/carrier-io/galloper.git code/galloper
  displayName: 'Get code to scan'

- bash: |
    docker run --rm -v `pwd`:/data getcarrier/sast:2.0 run -c /data/carrier-config.yml -s sast
  env:
    BUILD_ID: $(sample_secret)
  displayName: 'Run SAST scanning'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'sast-report.html'
    artifactType: 'pipeline'
  displayName: 'Save report'
